[package]
name = "driver-host"
license = "MIT"
repository = "https://github.com/cosmic-initiative/cosmic-initiative.git"

version = "0.3.14"

edition = "2021" 
authors = []
homepage = "https://starlane.io"
description="..."




[dependencies]

tokio = { version="1.40.0", features=["full"] }
anyhow = "1.0.86"
futures = { version = "0.3" }
futures-core = "0.3.30"
wasmer = "4.3.7"
wasmer-wasix = "0.27.0"
virtual-fs = "0.16.0"
