name: Rust

on:
  push:
    branches: [ "main", "develop", "feature/github-actions2" ]
  pull_request:
    branches: [ "main", "develop", "feature/github-actions2" ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash
    working-directory: rust 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test
       working-directory: ./starlane-macros
